language: java

jdk:
- openjdk8

branches:
  only:
  - develop

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

jobs:
  include:
    - stage: build
      before_install:
        - echo -e "INSTALL..."
      script:
        - mvn clean install -Pdev

    - stage: deploy
      before_install:
        - echo -e "RUNNING..."
      script:
        - mvn package -Pprod

after_success:
  - bash <(curl -s https://codecov.io/bash)
