language: java

jdk:
- openjdk8

branches:
  only:
  - develop

stages:
  - name: build
  - name: deploy

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

jobs:
  include:
    - stage: build
      before_install:
        - echo -e "INSTALL..."
      script:
        - mvn clean install

    - stage: deploy
      before_install:
        - echo -e "RUNNING..."
      script:
        - mvn package
